---
- name: Install sqlite3 for backups
  apt:
    pkg:
      sqlite3

- name: Ensure data directory
  file:
    path="{{ zoomhub_data_path }}"
    owner="{{ admin_user }}"
    group="{{ admin_user }}"
    state=directory

- name: Install PostgreSQL library support
  apt:
    pkg: libpq-dev
