---
# https://www.digitalocean.com/community/tutorials/how-to-secure-postgresql-against-automated-attacks
- name: Allow incoming web server (private IP) traffic to PostgreSQL
  ufw:
    rule: allow
    proto: tcp
    from_ip: '{{web_server_private_ip}}'
    to: any
    to_port: '5432'

# NOTE: We tried setting the privileges via `geerlingguy.postgresql` but it
# failed during the same step:
- name: Ensure PostgreSQL admin user privileges are present
  become_user: postgres
  postgresql_privs:
    db: '{{postgres_database_name}}'
    role: '{{postgres_user_admin_name}}'
    objs: ALL_IN_SCHEMA
    privs: ALL

- name: Ensure PostgreSQL web user privileges are present
  become_user: postgres
  postgresql_privs:
    db: '{{postgres_database_name}}'
    role: '{{postgres_user_web_name}}'
    type: table
    schema: public
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE

# # TODO: Enable whenever PostgreSQL configuration changes:
# - name: Restart PostgreSQL
#   service:
#     name: postgresql
#     state: restarted
