stanzas:
  - type: webapp
    exec: ../zoomhub
    hosts:
      - 104.239.163.79 # staging
      - 162.242.218.98 # production
      - api.zoom.it
      - api.zoomhub.net
      - openzoom.net
      - openzoom.org
      - staging.zoom.it
      - staging.zoomhub.net
      - staging.zoomhub.org
      - www.zoom.it
      - www.zoomhub.net
      - zoom.it
      - zoomhub.net
    forward-env:
      - PGDATABASE
      - PGHOST
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PROCESS_CONTENT
      - RACKSPACE_API_KEY
      - RACKSPACE_CONTAINER
      - RACKSPACE_CONTAINER_PATH
      - RACKSPACE_USERNAME
      - TEMP_PATH
